export const procedures = [
  "Regular Checkup",
  "Teeth Cleaning & Scaling",
  "Dental Filling",
  "Root Canal Treatment",
  "Crown Placement",
  "Tooth Extraction",
  "Dental Implant",
  "Orthodontic Treatment",
  "Periodontal Treatment",
  "Oral Surgery",
  "Cosmetic Dentistry",
  "Denture Fitting",
];

export const teeth = [
  "11 (Upper Right Central)",
  "12 (Upper Right Lateral)",
  "13 (Upper Right Canine)",
  "14 (Upper Right 1st Premolar)",
  "15 (Upper Right 2nd Premolar)",
  "16 (Upper Right 1st Molar)",
  "17 (Upper Right 2nd Molar)",
  "18 (Upper Right 3rd Molar)",
  "21 (Upper Left Central)",
  "22 (Upper Left Lateral)",
  "23 (Upper Left Canine)",
  "24 (Upper Left 1st Premolar)",
  "25 (Upper Left 2nd Premolar)",
  "26 (Upper Left 1st Molar)",
  "27 (Upper Left 2nd Molar)",
  "28 (Upper Left 3rd Molar)",
  "31 (Lower Left Central)",
  "32 (Lower Left Lateral)",
  "33 (Lower Left Canine)",
  "34 (Lower Left 1st Premolar)",
  "35 (Lower Left 2nd Premolar)",
  "36 (Lower Left 1st Molar)",
  "37 (Lower Left 2nd Molar)",
  "38 (Lower Left 3rd Molar)",
  "41 (Lower Right Central)",
  "42 (Lower Right Lateral)",
  "43 (Lower Right Canine)",
  "44 (Lower Right 1st Premolar)",
  "45 (Lower Right 2nd Premolar)",
  "46 (Lower Right 1st Molar)",
  "47 (Lower Right 2nd Molar)",
  "48 (Lower Right 3rd Molar)",
  "Full mouth",
  "Multiple teeth",
];

export const dosageMappings: Record<
  string,
  { timing: string; frequency: string }
> = {
  "1-0-0": { timing: "Before Food", frequency: "Once daily" },
  "0-1-0": { timing: "After Food", frequency: "Once daily" },
  "0-0-1": { timing: "After Food", frequency: "Once daily" },
  "1-1-0": { timing: "After Food", frequency: "Twice daily" },
  "1-0-1": { timing: "After Food", frequency: "Twice daily" },
  "0-1-1": { timing: "After Food", frequency: "Twice daily" },
  "1-1-1": { timing: "After Food", frequency: "Thrice daily" },
  "2-1-1": { timing: "After Food", frequency: "Four times daily" },
};